### ISSUE TITLE
Black Screen instead of background removal with Webcam - OBS 28.1.2 Windows 10

### ISSUE THREAD

**Issue by Woodz42** [royshil/obs-backgroundremoval#133]
Dear community,
When I am adding the filter "Background removal" to my Logitech Webcam Video Capturing Device I just get a black screen. Not filtering. Adjusting sliders does not do anything.
Any idea?
Thanks!
Best regards
Michael

**Comment by umireon** [comment]
I've released v0.5.8 on my own fork which can be installed with OBS 28+.
https://github.com/umireon/obs-backgroundremoval/releases/tag/v0.5.8

Can you check the new release works with your configuration?

**Comment by royshil** [comment]
try our new release https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.1 !

**Comment by royshil** [comment]
closing stale issue

**Comment by OUTofFIRE** [comment]
Even with the new release, even if i install from the installer, or drag the files, or unzip directly into the OBS folder, i still have the black screen, with flickering image every once in a while...

**Comment by umireon** [comment]
A new release v0.5.16 is not yet out, please wait for v0.5.16 is released!
